# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import os,sys
import DynamicSolver

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        # MainWindow.resize(503, 432)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalTabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalTabWidget.sizePolicy().hasHeightForWidth())
        self.verticalTabWidget.setSizePolicy(sizePolicy)
        self.verticalTabWidget.setObjectName(_fromUtf8("verticalTabWidget"))
        self.solveTab = QtGui.QWidget()
        self.solveTab.setObjectName(_fromUtf8("solveTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.solveTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.solveTab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.btnStudyDir = QtGui.QPushButton(self.solveTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStudyDir.sizePolicy().hasHeightForWidth())
        self.btnStudyDir.setSizePolicy(sizePolicy)
        self.btnStudyDir.setObjectName(_fromUtf8("btnStudyDir"))
        self.gridLayout.addWidget(self.btnStudyDir, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.solveTab)
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label = QtGui.QLabel(self.solveTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.btnCase = QtGui.QPushButton(self.solveTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCase.sizePolicy().hasHeightForWidth())
        self.btnCase.setSizePolicy(sizePolicy)
        self.btnCase.setObjectName(_fromUtf8("btnCase"))
        self.gridLayout_5.addWidget(self.btnCase, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.solveTab)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_3 = QtGui.QLabel(self.solveTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.btnDyr = QtGui.QPushButton(self.solveTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDyr.sizePolicy().hasHeightForWidth())
        self.btnDyr.setSizePolicy(sizePolicy)
        self.btnDyr.setObjectName(_fromUtf8("btnDyr"))
        self.gridLayout_4.addWidget(self.btnDyr, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.solveTab)
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_4 = QtGui.QLabel(self.solveTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.btnDLL = QtGui.QPushButton(self.solveTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDLL.sizePolicy().hasHeightForWidth())
        self.btnDLL.setSizePolicy(sizePolicy)
        self.btnDLL.setObjectName(_fromUtf8("btnDLL"))
        self.gridLayout_6.addWidget(self.btnDLL, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.solveTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_5 = QtGui.QLabel(self.solveTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_7.addWidget(self.label_5, 0, 0, 1, 1)
        self.txtZoneNum = QtGui.QLineEdit(self.solveTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtZoneNum.sizePolicy().hasHeightForWidth())
        self.txtZoneNum.setSizePolicy(sizePolicy)
        self.txtZoneNum.setObjectName(_fromUtf8("txtZoneNum"))
        self.gridLayout_7.addWidget(self.txtZoneNum, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_6 = QtGui.QLabel(self.solveTab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_8.addWidget(self.label_6, 0, 0, 1, 1)
        self.txtFault = QtGui.QLineEdit(self.solveTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtFault.sizePolicy().hasHeightForWidth())
        self.txtFault.setSizePolicy(sizePolicy)
        self.txtFault.setToolTip(_fromUtf8(""))
        self.txtFault.setObjectName(_fromUtf8("txtFault"))
        self.gridLayout_8.addWidget(self.txtFault, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_8)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_11 = QtGui.QLabel(self.solveTab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_7.addWidget(self.label_11)
        self.comboBoxTripType = QtGui.QComboBox(self.solveTab)
        self.comboBoxTripType.setObjectName(_fromUtf8("comboBoxTripType"))
        self.comboBoxTripType.addItem(_fromUtf8(""))
        self.comboBoxTripType.addItem(_fromUtf8(""))
        self.comboBoxTripType.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.comboBoxTripType)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_12 = QtGui.QLabel(self.solveTab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_8.addWidget(self.label_12)
        self.txtFrom = QtGui.QLineEdit(self.solveTab)
        self.txtFrom.setObjectName(_fromUtf8("txtFrom"))
        self.horizontalLayout_8.addWidget(self.txtFrom)
        self.label_13 = QtGui.QLabel(self.solveTab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_8.addWidget(self.label_13)
        self.txtTo1 = QtGui.QLineEdit(self.solveTab)
        self.txtTo1.setObjectName(_fromUtf8("txtTo1"))
        self.horizontalLayout_8.addWidget(self.txtTo1)
        self.label_14 = QtGui.QLabel(self.solveTab)
        self.label_14.setEnabled(False)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_8.addWidget(self.label_14)
        self.txtTo2 = QtGui.QLineEdit(self.solveTab)
        self.txtTo2.setEnabled(False)
        self.txtTo2.setObjectName(_fromUtf8("txtTo2"))
        self.horizontalLayout_8.addWidget(self.txtTo2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.pushButton = QtGui.QPushButton(self.solveTab)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_3.addWidget(self.pushButton)
        self.verticalTabWidget.addTab(self.solveTab, _fromUtf8(""))
        self.plotting = QtGui.QWidget()
        self.plotting.setObjectName(_fromUtf8("plotting"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.plotting)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_21 = QtGui.QLabel(self.plotting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout.addWidget(self.label_21)
        self.btnOutFile = QtGui.QPushButton(self.plotting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOutFile.sizePolicy().hasHeightForWidth())
        self.btnOutFile.setSizePolicy(sizePolicy)
        self.btnOutFile.setStatusTip(_fromUtf8(""))
        self.btnOutFile.setObjectName(_fromUtf8("btnOutFile"))
        self.horizontalLayout.addWidget(self.btnOutFile)
        self.outFileName = QtGui.QLabel(self.plotting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outFileName.sizePolicy().hasHeightForWidth())
        self.outFileName.setSizePolicy(sizePolicy)
        self.outFileName.setText(_fromUtf8(""))
        self.outFileName.setObjectName(_fromUtf8("outFileName"))
        self.horizontalLayout.addWidget(self.outFileName)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_18 = QtGui.QLabel(self.plotting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_5.addWidget(self.label_18)
        self.checkBox = QtGui.QCheckBox(self.plotting)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_5.addWidget(self.checkBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_20 = QtGui.QLabel(self.plotting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_9.addWidget(self.label_20)
        self.checkBox_3 = QtGui.QCheckBox(self.plotting)
        self.checkBox_3.setText(_fromUtf8(""))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.horizontalLayout_9.addWidget(self.checkBox_3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 6, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_16 = QtGui.QLabel(self.plotting)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_3.addWidget(self.label_16)
        self.lineEdit_5 = QtGui.QLineEdit(self.plotting)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_3.addWidget(self.lineEdit_5)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_19 = QtGui.QLabel(self.plotting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_6.addWidget(self.label_19)
        self.checkBox_2 = QtGui.QCheckBox(self.plotting)
        self.checkBox_2.setText(_fromUtf8(""))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayout_6.addWidget(self.checkBox_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_17 = QtGui.QLabel(self.plotting)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_4.addWidget(self.label_17)
        self.lineEdit_6 = QtGui.QLineEdit(self.plotting)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_4.addWidget(self.lineEdit_6)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_15 = QtGui.QLabel(self.plotting)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_2.addWidget(self.label_15)
        self.lineEdit_4 = QtGui.QLineEdit(self.plotting)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_2.addWidget(self.lineEdit_4)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.btnPlot = QtGui.QPushButton(self.plotting)
        self.btnPlot.setObjectName(_fromUtf8("btnPlot"))
        self.verticalLayout_5.addWidget(self.btnPlot)
        self.btnPlot.raise_()
        self.btnPlot.raise_()
        self.verticalTabWidget.addTab(self.plotting, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.verticalTabWidget)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.txtProgress = QtGui.QTextBrowser(self.centralwidget)
        self.txtProgress.setObjectName(_fromUtf8("txtProgress"))
        self.verticalLayout_4.addWidget(self.txtProgress)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.verticalTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_2.setText(_translate("MainWindow", "Study Directory:", None))
        self.btnStudyDir.setToolTip(_translate("MainWindow", "Select a study directory for the output files", None))
        self.btnStudyDir.setText(_translate("MainWindow", "Select", None))
        self.label.setText(_translate("MainWindow", "Case File:", None))
        self.btnCase.setToolTip(_translate("MainWindow", "Select the .sav file for the basecase", None))
        self.btnCase.setText(_translate("MainWindow", "Select", None))
        self.label_3.setText(_translate("MainWindow", "Dyr File:", None))
        self.btnDyr.setToolTip(_translate("MainWindow", "Select the .dyr file for dynamic data", None))
        self.btnDyr.setText(_translate("MainWindow", "Select", None))
        self.label_4.setText(_translate("MainWindow", "DLL File:", None))
        self.btnDLL.setToolTip(_translate("MainWindow", "Select ds.dll user model file", None))
        self.btnDLL.setText(_translate("MainWindow", "Select", None))
        self.label_5.setText(_translate("MainWindow", "Zone Number", None))
        self.txtZoneNum.setToolTip(_translate("MainWindow", "Zone Number to monitor voltages, Seperate multiple zones by space", None))
        self.label_6.setText(_translate("MainWindow", "Fault Bus Number", None))
        self.label_11.setText(_translate("MainWindow", "Trip:", None))
        self.comboBoxTripType.setToolTip(_translate("MainWindow", "Select the desired outage post fault", None))
        self.comboBoxTripType.setItemText(0, _translate("MainWindow", "Branch", None))
        self.comboBoxTripType.setItemText(1, _translate("MainWindow", "Three winding Transformer", None))
        self.comboBoxTripType.setItemText(2, _translate("MainWindow", "Generation Unit", None))
        self.label_12.setText(_translate("MainWindow", "From", None))
        self.label_13.setText(_translate("MainWindow", "to", None))
        self.label_14.setText(_translate("MainWindow", "to", None))
        self.pushButton.setText(_translate("MainWindow", "Solve", None))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.solveTab), _translate("MainWindow", "Dynamic Run", None))
        self.label_21.setText(_translate("MainWindow", ".Out File", None))
        self.btnOutFile.setToolTip(_translate("MainWindow", "Select .out file to plot the figuers", None))
        self.btnOutFile.setText(_translate("MainWindow", "Select", None))
        self.label_18.setText(_translate("MainWindow", "Frequency", None))
        self.label_20.setText(_translate("MainWindow", "Statcom", None))
        self.label_16.setText(_translate("MainWindow", "Motors Buses", None))
        self.lineEdit_5.setToolTip(_translate("MainWindow", "Enter bus numbers with space in between", None))
        self.label_19.setText(_translate("MainWindow", "SVC", None))
        self.label_17.setText(_translate("MainWindow", "Voltages Buses", None))
        self.lineEdit_6.setToolTip(_translate("MainWindow", "Enter bus numbers with space in between", None))
        self.label_15.setText(_translate("MainWindow", "Title:", None))
        self.lineEdit_4.setToolTip(_translate("MainWindow", "Title for the figuers", None))
        self.btnPlot.setText(_translate("MainWindow", "Plot", None))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.plotting), _translate("MainWindow", "Plotting", None))

    def on_StudyDir(self):
        self.dirpath = QtGui.QFileDialog.getExistingDirectory(MainWindow,'Select Folder', 'C:\\')
        self.label_7.setText(self.dirpath)

    def initDynamicSolver(self):
        self.s = DynamicSolver.DynamicSolver()

    def on_Solve(self):
        if self.txtZoneNum.text() == "":
            pass
        zone = int(self.txtZoneNum.text())
        fault = int(self.txtFault.text())
        # self.initDynamicSolver()
        self.triptype(self.comboBoxTripType.currentIndex())
        self.s.sig.connect(self.print_msg)
        self.s.init(self.dirpath, self.dyrfile, self.dllfile, self.casefile, fault, zone, self.tripBuses,self.tripType)
        self.s.start()
        # self.s.solve()
        # self.s.terminate()
    def print_msg(self,msg):
        self.txtProgress.append(msg)
    def on_Plot(self):
        title = unicode(self.lineEdit_4.text(),encoding="UTF-8")
        motors = unicode(self.lineEdit_5.text(),encoding="UTF-8").split()
        volts = unicode(self.lineEdit_6.text(),encoding="UTF-8").split()
        if self.s.solved:
            outfile = unicode(self.outFileName.text(),encoding="UTF-8")
        else:
            try:
                outfile = unicode(self.outfile,encoding="UTF-8")
            except:
                outfile = None
                pass
        bFreq = self.checkBox.isChecked()
        bSvc = self.checkBox_2.isChecked()
        bStatcom = self.checkBox_3.isChecked()
        self.plotting = DynamicSolver.Plotting(title,motors,volts,bFreq,bSvc,bStatcom,outfile,self.s.solved)
        self.plotting.sig.connect(self.print_msg)
        self.plotting.start()

    def on_Case(self):
        self.casefile = QtGui.QFileDialog.getOpenFileName(MainWindow,'Open File', 'C:\\',"SAV files (*.sav)")
        self.label_8.setText(self.casefile)
    def on_Dyr(self):
        self.dyrfile = QtGui.QFileDialog.getOpenFileName(MainWindow,'Open File', 'C:\\',"DYR files (*.dyr)")
        self.label_9.setText(self.dyrfile)
    def on_DLL(self):
        self.dllfile = QtGui.QFileDialog.getOpenFileName(MainWindow,'Open File', 'C:\\',"DLL files (*.dll)")
        self.label_10.setText(self.dllfile)
    def triptype(self,i):
        f = self.txtFrom.text()
        t1 = self.txtTo1.text()
        t2 = self.txtTo2.text()
        if i == 1:
            self.tripType = 1
            # Three winding trip
            self.label_13.setEnabled(True)
            self.txtTo1.setEnabled(True)
            self.label_14.setEnabled(True)
            self.txtTo2.setEnabled(True)
            self.label_12.setText('From:')
            self.tripBuses = []
            self.tripBuses = [f, t1, t2]
        elif i == 2:
            self.tripType = 2
            # Trip Generation Unit
            self.label_13.setEnabled(False)
            self.txtTo1.setEnabled(False)
            self.label_14.setEnabled(False)
            self.txtTo2.setEnabled(False)
            self.label_12.setText('Generation Bus:')
            self.tripBuses = []
            self.tripBuses = [f]
        else:
            self.tripType = 0
            # Trip Branch
            self.label_13.setEnabled(True)
            self.txtTo1.setEnabled(True)
            self.label_14.setEnabled(False)
            self.txtTo2.setEnabled(False)
            self.label_12.setText('From:')
            self.tripBuses = []
            self.tripBuses = [f, t1]

    def on_Outfile(self):
        self.outfile = QtGui.QFileDialog.getOpenFileName(MainWindow,'Open File', 'C:\\',"OUT files (*.out)")
        self.outFileName.setText(self.outfile)
    def TabChanged(self):
        if self.s.solved:
            name = str(self.s.dirpath+'\\'+self.s.outfile)
            self.outFileName.setText(name)


if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.initDynamicSolver()
    ui.statusBar.showMessage('Abdullah Al-Othman')
    ui.btnStudyDir.pressed.connect(ui.on_StudyDir)
    ui.btnCase.pressed.connect(ui.on_Case)
    ui.btnDyr.pressed.connect(ui.on_Dyr)
    ui.btnDLL.pressed.connect(ui.on_DLL)
    ui.pushButton.pressed.connect(ui.on_Solve)
    ui.btnPlot.pressed.connect(ui.on_Plot)
    ui.btnOutFile.pressed.connect(ui.on_Outfile)
    ui.comboBoxTripType.activated.connect(ui.triptype)
    ui.verticalTabWidget.currentChanged.connect(ui.TabChanged)
    MainWindow.show()
    sys.exit(app.exec_())