# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-15 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'statement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatementFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrydate', models.DateField(db_column='entrydate')),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statementFact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatementRow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rowOrder', models.IntegerField(blank=True, null=True)),
                ('rowTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('rowDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('rowProperties', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'statementRow',
                'managed': False,
            },
        ),
    ]
