# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'statement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatementRow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rowOrder', models.IntegerField(blank=True, null=True)),
                ('rowTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('rowDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('rowProperties', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'statementRow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatementFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('companyId', models.ForeignKey(db_column='companyId', on_delete=django.db.models.deletion.CASCADE,
                                                to='dbmaker.Company')),
                ('statementRowId',
                 models.ForeignKey(db_column='statementRowId', on_delete=django.db.models.deletion.CASCADE,
                                   to='dbmaker.StatementRow')),
            ],
            options={
                'db_table': 'statementFact',
            },
        ),
    ]
